### PR TITLE
Create pumpkin-cryptvine,yml

### PR DESCRIPTION
**Pull request by ILoveStarOcean2**

### CODE REVIEW

**Comment by seiyria** [comment]
Needs cryptvine image.

**Comment by ILoveStarOcean2** [comment]
Uploaded

**Comment by seiyria** [comment]
Make sure you're doing it on the right branch! Right now you're on the `patch-3` branch. You can see which branch you're on up here: https://i.imgur.com/It8x2zF.png

**Comment by ILoveStarOcean2** [comment]
Ok I will upload into Patch 1 only.

**Comment by ILoveStarOcean2** [comment]
I cant upload images into master atm.

**Comment by seiyria** [comment]
This pull request is on patch 3, so you need to put it on that branch.

**Comment by seiyria** [comment]
thanks! looks good.

**Comment by ILoveStarOcean2** [comment]
Yes, let me know when everything is ready for viewing.

**Pull request merged**
