### PR TITLE
Create cave-guardian.yml

### PR DESCRIPTION
**Pull request by ILoveStarOcean2**

### CODE REVIEW

**Comment by seiyria** [comment]
please grab the correct image from our dropbox and upload it to the boss directory. thanks!

**Comment by ILoveStarOcean2** [comment]
No image for cave guardian in the dropbox

**Comment by seiyria** [comment]
There isn't one in the JP folder either? https://www.dropbox.com/home/Star%20Ocean%20Anamnesis%20Resources/Enemies_JP

**Comment by ILoveStarOcean2** [comment]
No, that second one next to Lezard looks like Cave Guardian-ish, but I do
not believe that is Cave Guardian.

**Comment by seiyria** [comment]
Is it this one? 
image

**Comment by ILoveStarOcean2** [comment]
Yes

**Pull request merged**
