### PR TITLE
Update defender.yml

### PR DESCRIPTION
**Pull request by Coy47**

### CODE REVIEW

**Comment by seiyria** [comment]
Should the other one be closed in favor of this one?

**Comment by Coy47** [comment]
This one works, think patch 14 didn't because you edited the file while I had the old one open and it broke it when I submitted the older patch.

**Comment by seiyria** [comment]
I don't think I edited that one but if this one is set I'll close that one.

**Comment by Coy47** [comment]
Yeah close the other one, also I don't remember the meta data tags, but anyway, for whatever reason this one works the other one doesn't.

**Comment by seiyria** [comment]
The meta is new and I'll be writing about it a bit later!

**Pull request merged**
